### PR TITLE
Technical Debt: Next.js legacy components and folder structure

### PR DESCRIPTION
**Pull request by shon-button**
[Addresses](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/111) 

- Add client/app folder for page routing
- Add client/app/api folder for API routing (e.g., /api/hello)
- Add client/app/layout.tsx for the application-level layout
- Add client/app/components as an example
- Add client/app/styles as an example
- Add client/redux folder for Redux and Redux Toolkit files
- Add application state demo pages:
  - Setting count state: client/app/page.tsx
  - Displaying count state: client/app/display/page.tsx

**Demo steps**:

1. Open terminal in cas-registration\client folder
2. Start the development server:
   ```
   yarn dev
   ```
3. In your web browser, navigate to `http://localhost:3000/`

4. Interact with the Counter Page:
   - You should now see the counter page.
   - Use the "+" and "-" buttons to increment and decrement the counter value by 1.
   - You can also use the "Add Amount" button to increment the counter by a specific amount. Enter a value in the input field and click the button.
   - Similarly, you can use the "Add Amount Async" button to increment the counter asynchronously (calls http://localhost:3000/api/counter)

5. To view the application state value for the counter,  click the "Display" link.

image

image

### CODE REVIEW

**Review by Sepehr-Sobhani — APPROVED** [review]
This looks great and I have nothing to add 🤩
Just a question, Would it be better to use RTK Query instead of fetch API? If so, what would be the structure of the API calls?

**Comment by shon-button** [comment]
Thanks for the review, Sepehr.
Using fetch() as the Next.js routes extend from the native Web fetch API.
Certainly possible to use a different fetching toolkit if required.
:)

**Comment by Sepehr-Sobhani** [comment]
> Thanks for the review, Sepehr. Using fetch() as the Next.js routes extend from the native Web fetch API. Certainly possible to use a different fetching toolkit if required. :)

Another question, How do we handle `Optimistic Response`, `Caching` and `Tracking loading state`?

**Comment by shon-button** [comment]
Re: How do we handle Optimistic Response, Caching and Tracking loading state 
Example: [Authentication using Redux slice with optimistic updates, caching, and loading state tracking](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/119)

**Pull request merged**
