### PR TITLE
fix: e2e dashboard screenshot diffs due to role difference

### PR DESCRIPTION
**Pull request by marcellmueller**
Fix for Happo diffs due to e2e user role differences.

### CODE REVIEW

**Review by shon-button — APPROVED** [review]

**Comment by shon-button** [comment]
@marcellmueller 
needs to be deleted?
 `client/e2e/pages/onboarding/home/page.spec.ts-snapshots`

**Comment by shon-button** [comment]
@marcellmueller could you please provide a screenshot of the happo report which allows accept\reject actions?

**Comment by marcellmueller** [comment]
> @marcellmueller could you please provide a screenshot of the happo report which allows accept\reject actions?

All of the reports should allow it on the left side of the report. I may ask you to sign in if you haven't. Also I deleted those playwright screenshots thank you!

Screenshot 2024-03-14 at 8 25 47 AM

**Comment by shon-button** [comment]
> > @marcellmueller could you please provide a screenshot of the happo report which allows accept\reject actions?
> 
> All of the reports should allow it on the left side of the report. I may ask you to sign in if you haven't. Also I deleted those playwright screenshots thank you!
> 
> Screenshot 2024-03-14 at 8 25 47 AM

Mine's not as nice! Any insight as to why I am not seeing the left navigator?
thanks :)

image

**Comment by marcellmueller** [comment]
> @marcellmueller Mine's not as nice! Any insight as to why I am not seeing the left navigator? thanks :)

That's very strange, it shouldn't be an auth issue. I have tried it in incognito mode in Chromium, Firefox and Safari and get the sidebar. Can you try that in some other browsers to confirm? 

Safari incognito mode:
Screenshot 2024-03-14 at 11 10 09 AM

**Comment by shon-button** [comment]
> > @marcellmueller Mine's not as nice! Any insight as to why I am not seeing the left navigator? thanks :)
> 
> That's very strange, it shouldn't be an auth issue. I have tried it in incognito mode in Chromium, Firefox and Safari and get the sidebar. Can you try that in some other browsers to confirm?
> 
> You don't even need direct Happo access to review, any user that has access to our GitHub repo can review diffs. https://docs.happo.io/docs/user-roles
> 
> Safari incognito mode: Screenshot 2024-03-14 at 11 10 09 AM

@marcellmueller 

FYI: closing the circle on the report screen differences
- Opening report from Happo `Dashboard` does NOT display `Review:Accept\Reject` functionality
- Opening report from PR's Happo `Details` does display `Review:Accept\Reject` functionality

image

**Pull request merged**
