### PR TITLE
387 add custom history user

### PR DESCRIPTION
**Pull request by Sepehr-Sobhani**
[ISSUE 387](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=48609626)

### CODE REVIEW

**Review by andrea-williams — COMMENTED** [review]
Do we also need to capture the date of the change along with the user ID, or is that automatically captured by the django history package (don't know the proper name for it) we're using?

**Comment by Sepehr-Sobhani** [comment]
> Do we also need to capture the date of the change along with the user ID, or is that automatically captured by the django history package (don't know the proper name for it) we're using?
> 
> Also flagging for you that there's a merge conflict in one of the migration files. Probably because I took too long to review this. Sorry!

That's correct, django simple history package by default takes care of the `created_at` and `updated_at` data fields.
No worries, Thanks for reviewing this PR :)

**Review by andrea-williams — APPROVED** [review]
Code LGTM so I'm happy, although it looks like the action for backend tests failed???

**Comment by Sepehr-Sobhani** [comment]
> Code LGTM so I'm happy, although it looks like the action for backend tests failed???

Should be fixed now, Thank you!

**Pull request merged**
