### PR TITLE
2497 cas roles

### PR DESCRIPTION
**Pull request by BCerki**
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=88009826&issue=bcgov%7Ccas-registration%7C2497

Some of the AC for this ticket was covered by the other role-related tickets. This PR:
- removes the internal_admin dashboards (all cas roles can view everything now). I couldn't delete the internal_admin.json without breaking existing migrations, so I left the jsons in but made a new migration
- vitest to confirm correct roles for BORO/BCGHG ID
- transfers page.tsx for cas_admin (I know this is also coming in the transfers PR, but I thought it might be confusing in PO review of this ticket if the grid wasn't visible)

### CODE REVIEW

**Review by Sepehr-Sobhani — APPROVED** [review]
🤩

**Comment by Sepehr-Sobhani** [comment]
@BCerki Oops! We lost my changes :D

**Comment by BCerki** [comment]
> @BCerki Oops! We lost my changes :D

Ahhhhh, sorry!!

**Comment by Sepehr-Sobhani** [comment]
> > @BCerki Oops! We lost my changes :D
> 
> Ahhhhh, sorry!! Do you still have them locally? Otherwise I can put them back in

No worries! you have it now.

**Comment by BCerki** [comment]
> > > @BCerki Oops! We lost my changes :D
> > 
> > 
> > Ahhhhh, sorry!! Do you still have them locally? Otherwise I can put them back in
> 
> No worries! you have it now.

Saving the day as usual

**Pull request merged**
