### PR TITLE
Chore/django simple history

### PR DESCRIPTION
**Pull request by dleard**
Adding the django-simple-history package to track changes to our user-controlled data tables.
This will:
- Add an erc_history schema to hold all the _history tables
- Add _history tables to all user-controlled data tables
- On any change to those tables, the snapshot of the data will be recorded and timestamped in the _history table

To test this manually:
- Using the app (or at least the endpoint), make a change to any table.
- use psql or pgadmin to check that your change was saved to the corresponding <table>_history table
- (ex: `select * from erc_history.operation_history;` would show the change history for the operation table)

### CODE REVIEW

**Comment by shon-button** [comment]
I must be missing a step as I do not see the change history, return 0 rows:

 ###Steps taken:
 
 **1. Modify bc_obps/registration/models.py**
 ```
 class BusinessRole(models.Model):
    """
    Roles that a Contact can have within an operator/operation
    """

    role_name = models.CharField(
        primary_key=True,
        serialize=False,
        db_comment='The name identifying the role assigned to a Contact. Also acts as the primary key.',
        max_length=100,
    )
    role_description = models.CharField(db_comment='Description of the business role', max_length=1000)
    a_new_field = models.CharField(db_comment='New field description', max_length=255, null=True, blank=True)
    history = HistoricalRecords(table_name='erc_history"."business_role_history')

    class Meta:
        db_table_comment = "This table contains the definitions for roles within the operator/operation. These roles are used to define the permissions a user has within the operator/operation"
        db_table = 'erc"."business_role'
 ```
**2. Issue poetry commands:**
shon@pop-os:~/Workspace/CAS/cas-registration$ cd bc_obps
shon@pop-os:~/Workspace/CAS/cas-registration/bc_obps$ poetry shell
(registration-py3.9) shon@pop-os:~/Workspace/CAS/cas-registration/bc_obps$  pip install django-simple-history
(registration-py3.9) shon@pop-os:~/Workspace/CAS/cas-registration/bc_obps$ make migrations
python manage.py makemigrations
Migrations for 'registration':
  registration/migrations/0003_businessrole_a_new_field_and_more.py
    - Add field a_new_field to businessrole
    - Add field a_new_field to historicalbusinessrole
(registration-py3.9) shon@pop-os:~/Workspace/CAS/cas-registration/bc_obps$  make migrate
python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, registration, sessions
Running migrations:
  Applying registration.0003_businessrole_a_new_field_and_more... OK

**3. Issue psql commands:**
(registration-py3.9) shon@pop-os:~/Workspace/CAS/cas-registration/bc_obps$ psql
shon=# \c registration
registration=# SELECT * FROM erc.business_role;
          role_name          |                                 role_description                                  | a_new_field 
-----------------------------+-----------------------------------------------------------------------------------+-------------
 Authorized Signing Officer  | A person who has the authority to sign documents on behalf of the business.       | 
 Operation Registration Lead | A person who is responsible for registering operations on behalf of the business. | 
 Operation Representative    | A person who is responsible for the day-to-day operations of the business.        | 
 Senior Officer              | A person who has the authority to make decisions on behalf of the business.       | 
(4 rows)

registration=# SELECT * FROM erc_history.business_role_history;
 role_name | role_description | history_id | history_date | history_change_reason | history_type | history_user_id | a_new_field 
-----------+------------------+------------+--------------+-----------------------+--------------+-----------------+-------------
(0 rows)

**Comment by dleard** [comment]
@shon-button 
I don't believe it will track changes made in a migration. The change will have to happen inside the app because it's a Django package that requires the app to be running to apply any changes to the history tables.

**Comment by shon-button** [comment]
@dleard 

D' ohhhhhhhhhhh!

So, data changes in a table are tracked in history as well...but NOT the schema table changes?

**Comment by dleard** [comment]
> @dleard
> 
> D' ohhhhhhhhhhh!
> 
> So, data changes in a table are tracked in history...but NOT the schema table changes?

correct

**Review by shon-button — APPROVED** [review]

**Pull request merged**
