### PR TITLE
790 default role for user operator data model

### PR DESCRIPTION
**Pull request by Sepehr-Sobhani**
[ISSUE 790](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=51804153)

### CODE REVIEW

**Review by BCerki — COMMENTED** [review]
I'm getting some errors in both the backend and frontend consoles. They don't look particularly related to your PR, so unless you think they're introduced, we can make a bug ticket and this one can go in.

When I navigate to the select operator page:
image

When I submit the senior operator form:
image

**Comment by Sepehr-Sobhani** [comment]
> I'm getting some errors in both the backend and frontend consoles. They don't look particularly related to your PR, so unless you think they're introduced, we can make a bug ticket and this one can go in.
> 
> When I navigate to the select operator page: image
> 
> When I submit the senior operator form: image

For the first image, Is it happening for `bc-cas-dev-three`?
For the second one, you need to run `yarn` and `poetry install` to install sentry packages on both ends.

**Comment by BCerki** [comment]
> > I'm getting some errors in both the backend and frontend consoles. They don't look particularly related to your PR, so unless you think they're introduced, we can make a bug ticket and this one can go in.
> > When I navigate to the select operator page: image
> > When I submit the senior operator form: image
> 
> For the first image, Is it happening for `bc-cas-dev-three`? For the second one, you need to run `yarn` and `poetry install` to install sentry packages on both ends.

For the first one, it's `bc-cas-dev` with the `user_operator` table truncated. The second one--I've already run both of those

**Comment by Sepehr-Sobhani** [comment]
> > > I'm getting some errors in both the backend and frontend consoles. They don't look particularly related to your PR, so unless you think they're introduced, we can make a bug ticket and this one can go in.
> > > When I navigate to the select operator page: image
> > > When I submit the senior operator form: image
> > 
> > 
> > For the first image, Is it happening for `bc-cas-dev-three`? For the second one, you need to run `yarn` and `poetry install` to install sentry packages on both ends.
> 
> For the first one, it's `bc-cas-dev` with the `user_operator` table truncated. The second one--I've already run both of those. I'll try deleting the node_modules folder

OK, those two `404`s happen when there's no `user_operator` record for that specific user.

**Review by BCerki — APPROVED** [review]

**Pull request merged**
