### PR TITLE
1513 API auth header consistency

### PR DESCRIPTION
**Pull request by shon-button**
Addresses:
 [1513](https://github.com/bcgov/cas-registration/issues/1513)

## 🚀 Impact:

   -  updated API endpoints to retrieve the `user_guid` from the Authorization header instead of the endpoint parameter
   - updated `client/app/utils/actions.ts` to splice endpoint `user_guid` parameter
   - API calls from `client/app/api/auth/[...nextauth]/route.ts\callback jwt` return correct JSON data
   - updated API endpoint tests

##  🔬 Testing:

- Validate app login process initializes app user session as expected:
1. From terminal command, start the api server:
 ```
cd bc_obps
make reset_db
make run
```  
2.  From terminal command, start the app development server:
 ```
cd client && yarn dev
```  
3. Navigate to `http://localhost:3000`
4. Click a "Log in with Business BCeID" button
5. Sign in to Keycloak using `bc-cas-dev`
6. **Expected result**: redirection to `dashboard` page for role `industry_user_admin`
7. **Expected result**: no JSON errors in the app development server terminal
8. Click a "Log Out" button
9. Navigate to `http://localhost:3000`
10. Click a "Log in with Business BCeID" button
11. Sign in to Keycloak using `bc-cas-dev-secondary`
12. **Expected result**: redirection to `dashboard` page for role `industry_user`
13. **Expected result**: no JSON errors in the app development server terminal

- Validate `cd client && yarn test`  status is  `pass...` 
- Validate `cd bc_obps && make pythontests `  status is  `pass...` 
- Validate [e2e test](https://github.com/bcgov/cas-registration/actions/runs/8886389694) status is  `pass` 
image

### CODE REVIEW

**Review by Sepehr-Sobhani — COMMENTED** [review]
Looks great, Thank you! Not approving this since we have lots of happo diffs and I think we need to investigate the cause. Also, we have some instances of passing `user_guid` as query parameters which I think we need to remove:
- `actionHanlder` functions in: `client/app/api/auth/[...nextauth]/route.ts` 
- `user.js` file in `client/tests/performance/scenarios/backend/user.js`

**Comment by shon-button** [comment]
> Looks great, Thank you! Not approving this since we have lots of happo diffs and I think we need to investigate the cause. Also, we have some instances of passing `user_guid` as query parameters which I think we need to remove:
> 
> * `actionHanlder` functions in: `client/app/api/auth/[...nextauth]/route.ts`
> * `user.js` file in `client/tests/performance/scenarios/backend/user.js`

@Sepehr-Sobhani 
Thank-you for review.
The  `actionHanlder` functions in: `client/app/api/auth/[...nextauth]/route.ts` do require the query parameter so to set the user_guid in the Auhorization header if the call is made before the token is returned.

**Comment by Sepehr-Sobhani** [comment]
> Thank-you for review.
> The `actionHanlder` functions in: `client/app/api/auth/[...nextauth]/route.ts` do require the query parameter so to set the user_guid in the Auhorization header if the call is made before the token is returned.

Oh I see now, Thanks for clarifying that! 🙏 However, I still feel this is a bit confusing for another Sepehr in the future looking at this code :D

**Review by Sepehr-Sobhani — APPROVED** [review]
⭐

**Pull request merged**
