### PR TITLE
fix: store the state to prevent loosing it when switching tabs

### PR DESCRIPTION
**Pull request by Sepehr-Sobhani**
[ISSUE 986](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=54765288)

### CODE REVIEW

**Comment by shon-button** [comment]
Test steps:
1. "Create Operation"
2.  Upload an attachment
3. Click the (Download [template]) 
4. **Confirmed** attachment field retains text of the atachment
5. Click 'Submit`
6. Validation error on attachment field
image

**Comment by shon-button** [comment]
@Sepehr-Sobhani 

Perhaps a harder task to accomplish but, wanted to note that the attachment field text is cleared on `Back` Navigation

**Comment by Sepehr-Sobhani** [comment]
> @Sepehr-Sobhani
> 
> Perhaps a harder task to accomplish but, wanted to note that the attachment field text is cleared on `Back` Navigation

@shon-button Thanks for reviewing this pull request! I think the back navigation is not working intentionally because we handle the attachment upload to our buckets in the backend once the user hits the submit button. Could you please correct me if I'm wrong, @BCerki?

**Comment by BCerki** [comment]
> > @Sepehr-Sobhani
> > Perhaps a harder task to accomplish but, wanted to note that the attachment field text is cleared on `Back` Navigation
> 
> @shon-button Thanks for reviewing this pull request! I think the back navigation is not working intentionally because we handle the attachment upload to our buckets in the backend once the user hits the submit button. Could you please correct me if I'm wrong, @BCerki?

Yes, the attachment only saves once the user clicks submit. The rest of the form works that way too. If you fill out page 2 and click "Back", the form will wipe. It only saves if you click "Save and Continue" before clicking "Back"

**Review by shon-button — APPROVED** [review]
Nice ✨

**Pull request merged**
