### PR TITLE
1686 operations grid

### PR DESCRIPTION
**Pull request by BCerki**
card: https://github.com/bcgov/cas-registration/issues/1686 and https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=64981220

This PR:
- hooks up the internal and external operations grids to the dashboard tiles (grid itself was reviewed in previous PRs)
- puts placeholder components in the pages we haven't completed yet (I found it confusing to click on "Add Operation" and have it lead to what's technically a part 2 page but is just a copy of part 1)
- moves the reg1 utils into shared (needed for reg2 tests to work) and updates imports
- moves reg2 tests to reg2 (tests were already reviewed in previous PRs, this is just a file move)

Note--because our FE routes are organized by role, there are five copies of the new operations page, so when manual testing, try different roles to confirm things work for everyone.

### CODE REVIEW

**Review by Sepehr-Sobhani — CHANGES_REQUESTED** [review]
This looks great, Thank you!
We just need to update dashboard tiles in the database directly by querying the intended record and changing it. Updating fixtures doesn't get applied in DEV/TEST/PROD namespaces.

The process could be something like:
- `python manage.py makemigrations --empty common` to generate an empty migration(you can rename it to whatever later)
- Adding something like below to update one of the links:(⚠️ Not tested)
```python
from django.db import migrations


def update_operations_href(apps, schema_editor):
    DashboardData = apps.get_model('common', 'DashboardData')
    dashboard = DashboardData.objects.get(name="External BCiers Dashboard")
    data = dashboard.data

    # Find the registration tile
    registration_tile = next(tile for tile in data.get('tiles', []) if tile['title'] == 'Registration')

    # Find the operations link
    operations_link = next(link for link in registration_tile.get('links', []) if link['title'] == 'Operations')

    # Update the href of the operations link
    operations_link['href'] = '/registration/<new-operations-url>'

    dashboard.data = data
    dashboard.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', 'previous_migration_file'),
    ]

    operations = [
        migrations.RunPython(update_operations_href),
    ]
```

**Comment by BCerki** [comment]
> This looks great, Thank you! We just need to update dashboard tiles in the database directly by querying the intended record and changing it. Updating fixtures doesn't get applied in DEV/TEST/PROD namespaces.
> 
> The process could be something like:
> 
> * `python manage.py makemigrations --empty common` to generate an empty migration(you can rename it to whatever later)
> * Adding something like below to update one of the links:(⚠️ Not tested)
> 
> ```python
> from django.db import migrations
> 
> 
> def update_operations_href(apps, schema_editor):
>     DashboardData = apps.get_model('common', 'DashboardData')
>     dashboard = DashboardData.objects.get(name="External BCiers Dashboard")
>     data = dashboard.data
> 
>     # Find the registration tile
>     registration_tile = next(tile for tile in data.get('tiles', []) if tile['title'] == 'Registration')
> 
>     # Find the operations link
>     operations_link = next(link for link in registration_tile.get('links', []) if link['title'] == 'Operations')
> 
>     # Update the href of the operations link
>     operations_link['href'] = '/registration/<new-operations-url>'
> 
>     dashboard.data = data
>     dashboard.save()
> 
> 
> class Migration(migrations.Migration):
> 
>     dependencies = [
>         ('common', 'previous_migration_file'),
>     ]
> 
>     operations = [
>         migrations.RunPython(update_operations_href),
>     ]
> ```

@shon-button , I see some tile updates going on in your PR too: https://github.com/bcgov/cas-registration/pull/1868/files#diff-1a0fbb576e8de158e6aa831ab4d85f1c19a1afbca07b46731f3c5e6e837369f3. Want to coordinate on this tomorrow so we don't duplicate anything?

**Comment by Sepehr-Sobhani** [comment]
> > This looks great, Thank you! We just need to update dashboard tiles in the database directly by querying the intended record and changing it. Updating fixtures doesn't get applied in DEV/TEST/PROD namespaces.
> > The process could be something like:
> > 
> > * `python manage.py makemigrations --empty common` to generate an empty migration(you can rename it to whatever later)
> > * Adding something like below to update one of the links:(⚠️ Not tested)
> > 
> > ```python
> > from django.db import migrations
> > 
> > 
> > def update_operations_href(apps, schema_editor):
> >     DashboardData = apps.get_model('common', 'DashboardData')
> >     dashboard = DashboardData.objects.get(name="External BCiers Dashboard")
> >     data = dashboard.data
> > 
> >     # Find the registration tile
> >     registration_tile = next(tile for tile in data.get('tiles', []) if tile['title'] == 'Registration')
> > 
> >     # Find the operations link
> >     operations_link = next(link for link in registration_tile.get('links', []) if link['title'] == 'Operations')
> > 
> >     # Update the href of the operations link
> >     operations_link['href'] = '/registration/<new-operations-url>'
> > 
> >     dashboard.data = data
> >     dashboard.save()
> > 
> > 
> > class Migration(migrations.Migration):
> > 
> >     dependencies = [
> >         ('common', 'previous_migration_file'),
> >     ]
> > 
> >     operations = [
> >         migrations.RunPython(update_operations_href),
> >     ]
> > ```
> 
> @shon-button , I see some tile updates going on in your PR too: https://github.com/bcgov/cas-registration/pull/1868/files#diff-1a0fbb576e8de158e6aa831ab4d85f1c19a1afbca07b46731f3c5e6e837369f3. Want to coordinate on this tomorrow so we don't duplicate anything?

I see that @marcellmueller is also making updates to the tiles. If there are numerous changes, I recommend updating fixtures, clearing all existing dashboard data from the DB and executing the loadfixture command on a new migration file. This is probably the easiest approach.

**Comment by marcellmueller** [comment]
> I see that @marcellmueller is also making updates to the tiles. If there are numerous changes, I recommend updating fixtures, clearing all existing dashboard data from the DB and executing the loadfixture command on a new migration file. This is probably the easiest approach.

In CCBC we borrowed an idea from a CAS project, I'm not sure if it was `cas-cif` but the general idea was an api that ran when the application started up. It checked our form schema versions against versions in the database and if they were newer they would add a new record in the database with that version. 

I wonder if it's worth exploring something similar for both of these form schemas we will have to version but also the dashboard fixtures. It might be nicer than dealing with all of these migrations.

**Comment by Sepehr-Sobhani** [comment]
> > I see that @marcellmueller is also making updates to the tiles. If there are numerous changes, I recommend updating fixtures, clearing all existing dashboard data from the DB and executing the loadfixture command on a new migration file. This is probably the easiest approach.
> 
> In CCBC we borrowed an idea from a CAS project, I'm not sure if it was `cas-cif` but the general idea was an api that ran when the application started up. It checked our form schema versions against versions in the database and if they were newer they would add a new record in the database with that version.
> 
> I wonder if it's worth exploring something similar for both of these form schemas we will have to version but also the dashboard fixtures. It might be nicer than dealing with all of these migrations.

In my opinion, we can consider using that approach for versioning forms (if/when we decide to start versioning forms), but it would be overkill for dashboard tiles. For the dashboard tiles, we simply need an empty migration file that deletes existing dashboard tiles and loads new ones.

**Review by Sepehr-Sobhani — APPROVED** [review]
🤩

**Pull request merged**
